---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  client_rb:
    ssl_verify_mode: :verify_none # Chef outputs an ugly SSL warning otherwise

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kvexpress::default]
  - name: testsuite
    run_list:
      - recipe[kvexpress::test_lwrp]
    attributes:
      kvexpress:
        dogstatsd: true
      tags: kvexpress:canary
