---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: false
  client_rb:
    ssl_verify_mode: :verify_none # Chef outputs an ugly SSL warning otherwise

busser:
  root_path: /opt/busser

platforms:
  - name: datadog/ubuntu-12.04
  - name: datadog/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[dd-base::chow_repo]
      - recipe[dd-consul::default]
      - recipe[kvexpress::default]
      - recipe[kvexpress::lwrp_test]
    attributes:
      consul:
        service_mode: bootstrap
      tags: kvexpress:canary
